### ISSUE TITLE
(Error) Not working

### ISSUE THREAD

**Issue by ghost** [yuvraj108c/4k-video-upscaler-colab#6]
I uploaded a gif, but its shows [prediction failed](https://replicate.com/lucataco/real-esrgan-video) always. [Here is the file.](https://github.com/yuvraj108c/4k-video-upscaler-colab/assets/129925515/801ef20d-a64a-4707-ba8c-4c80752a36ba)

- Provide 2x, 3x, 4x parameters in resolution menu.
- When 2x is selected     - Upscale from 480x696 to 960x1392 and so on for 3x and 4x.

**Comment by yuvraj108c** [comment]
Hi, this notebook supports only mp4 videos

**Comment by ghost** [comment]
Thanks for the clarification.

> Provide 2x, 3x, 4x parameters in resolution menu.

- Please provide 2x, 3x, and 4x parameters in the resolution menu, so the upscaled video will have proper w x h based on the orginal video.
- [Original video ](https://github.com/yuvraj108c/4k-video-upscaler-colab/assets/129925515/f90c2479-70b1-42ff-9b44-8f6b4a3a1b12) (w x h) - 480 x 696
- [Upscaled video ](https://github.com/yuvraj108c/4k-video-upscaler-colab/assets/129925515/3e4c7ea3-6b83-4f4f-8f10-185804620cb1) (w x h) - 1324 x 1920, when full hd resolution is selected.
- Therefore, 2x of the above would be 960 x 1392 and 3x would be 1440 x 1998, etc.

**Comment by yuvraj108c** [comment]
ok, I'll add these options to the resolution dropdown!

**Comment by yuvraj108c** [comment]
Added the 2x/3x/4x scale options
